// 8 core themes — used in menu, hero node-grid, and sections.
export const THEMES = [
  {
    id: 'thinking',
    ru: 'Мышление',
    en: 'Thinking',
    short: 'Системное и стратегическое мышление, ментальные модели.',
    desc: 'Формирование мышления: ментальные модели, принятие решений, фокус.',
    color: '#7c5cff',
  },
  {
    id: 'marketing',
    ru: 'Маркетинг',
    en: 'Marketing',
    short: 'Полный стек маркетинга: воронки, контент, психология.',
    desc: 'SEO, копирайтинг, контент-стратегия, маркетинговая психология.',
    color: '#4aa3ff',
  },
  {
    id: 'earn',
    ru: 'Заработок',
    en: 'Earn',
    short: 'Модели монетизации и финансовые потоки.',
    desc: 'Источники дохода, продукты, продажи, денежный поток.',
    color: '#27e0c0',
  },
  {
    id: 'webdesign',
    ru: 'Веб дизайн',
    en: 'Web Design',
    short: 'Frontend и backend, дизайн-системы, лендинги.',
    desc: 'Full-stack веб-разработка и дизайн интерфейсов.',
    color: '#5cc8ff',
  },
  {
    id: '3d',
    ru: '3D моделирование',
    en: '3D Modeling',
    short: 'Blender, WebGL, 3D-сцены и ассеты.',
    desc: '3D-моделирование, рендер, real-time графика для веба.',
    color: '#9b6cff',
  },
  {
    id: 'audio',
    ru: 'Аудио дизайн',
    en: 'Audio Design',
    short: 'Создание и написание музыки, саунд-дизайн.',
    desc: 'Генерация музыки, аудио-продакшн, звуковое оформление.',
    color: '#ff6cc8',
  },
  {
    id: 'video',
    ru: 'Видео дизайн',
    en: 'Video Design',
    short: 'Создание видео, моушн, монтаж-пайплайны.',
    desc: 'Видео-продакшн, анимация, рендер композиций.',
    color: '#4a7bff',
  },
  {
    id: 'game',
    ru: 'Game дизайн',
    en: 'Game Design',
    short: 'Геймдизайн, механики, движки.',
    desc: 'Разработка игр: механики, ECS, движки и паттерны.',
    color: '#6c9bff',
  },
];

export const PALETTE = {
  bg0: '#05060f',
  bg1: '#0a0e24',
  blue: '#3aa0ff',
  cyan: '#27e0ff',
  violet: '#7c5cff',
  red: '#ff3b6b',
  gold: '#ffcc33',
  text: '#cfe0ff',
};
